/*
 * action types
 */


export const GET_ARTICLES_LIST = 'GET_ARTICLES_LIST';
export const GET_ARTICLES_LIST_SUCCESS = 'GET_ARTICLES_LIST_SUCCESS';
export const GET_ARTICLES_LIST_ERROR = 'GET_ARTICLES_LIST_ERROR';

export const GET_ARTICLE_INFO = 'GET_ARTICLE_INFO';
export const GET_ARTICLE_INFO_SUCCESS = 'GET_ARTICLE_INFO_SUCCESS';
export const GET_ARTICLE_INFO_ERROR = 'GET_ARTICLE_INFO_ERROR';

export const ADD_ARTICLE = 'ADD_ARTICLE';
export const ADD_ARTICLE_SUCCESS = 'ADD_ARTICLE_SUCCESS';
export const ADD_ARTICLE_ERROR = 'ADD_ARTICLE_ERROR';

export const REMOVE_ARTICLE = 'REMOVE_ARTICLE';
export const REMOVE_ARTICLE_SUCCESS = 'REMOVE_ARTICLE_SUCCESS';
export const REMOVE_ARTICLE_ERROR = 'REMOVE_ARTICLE_ERROR';

export const EDIT_ARTICLE = 'EDIT_ARTICLE';
export const EDIT_ARTICLE_SUCCESS = 'EDIT_ARTICLE_SUCCESS';
export const EDIT_ARTICLE_ERROR = 'EDIT_ARTICLE_ERROR';

export const REMOVE_COMMENT = 'REMOVE_COMMENT';

export const TOGGLE_UNSAFE_MODE = 'TOGGLE_UNSAFE_MODE';

export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR';

export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';

export const GET_USER_DETAILS = 'GET_USER_DETAILS';
export const GET_USER_DETAILS_SUCCESS = 'GET_USER_DETAILS_SUCCESS';
export const GET_USER_DETAILS_ERROR = 'GET_USER_DETAILS_ERROR';

export const LOG_OUT = 'LOG_OUT';
